name       : rstudio
version    : 0.99.903
release    : 1
source     :
    - https://github.com/rstudio/rstudio/archive/v0.99.903.tar.gz : 8902fe7a6f7f6e0d6e8fae2472e479bb9cbe9cbb2e0747e5f01a093d31993a3c
    - https://s3.amazonaws.com/rstudio-buildtools/gin-1.5.zip : f561f4eb5d5fe1cff95c881e6aed53a86e9f0de8a52863295a8600375f96ab94
    - https://s3.amazonaws.com/rstudio-buildtools/gwt-2.7.0.zip : aa65061b73836190410720bea422eb8e787680d7bc0c2b244ae6c9a0d24747b3
license    : AGPL-3.0
component  : programming.ide
summary    : Integrated development environment (IDE) for R.
description: |
    RStudio is an integrated development environment (IDE) for the R programming language.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libR)
    - pkgconfig(Qt5WebKit)
    - apache-ant
    - libboost-devel
    - shared-mime-info
    - xdg-utils
setup      : |
    GWT_VER=2.7.0
    GIN_VER=1.5
    mkdir -p src/gwt/lib/gwt
    unzip -qd . $sources/gwt-${GWT_VER}.zip
    mv gwt-${GWT_VER} src/gwt/lib/gwt/${GWT_VER}

    mkdir -p src/gwt/lib/gin/${GIN_VER}
    unzip -qd src/gwt/lib/gin/${GIN_VER} $sources/gin-${GIN_VER}.zip

    #Defeat build 'checks'
    cd dependencies/common
    install -d dictionaries libclang/{3.5,builtin-headers} mathjax-23 pandoc rmarkdown rsconnect
    cd ../..

    %cmake -DRSTUDIO_TARGET=Desktop \
           -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake \
           -DCMAKE_INSTALL_PREFIX=/usr/share/rstudio
build      : |
    %make
install    : |
    %make_install
    install -d -m 00755 $installdir/usr/bin
    ln -s /usr/share/rstudio/bin/rstudio $installdir/usr/bin/rstudio

    #Use system dictionaries
    rm -rf $installdir/usr/share/rstudio/resources/dictionaries
    ln -s /usr/share/hunspell $installdir/usr/share/rstudio/resources/dictionaries
