name       : rstudio
version    : 1.4.1717
release    : 23
source     :
    - https://github.com/rstudio/rstudio/archive/v1.4.1717.tar.gz : 3af234180fd7cef451aef40faac2c7b52860f14a322244c1c7aede029814d261
license    : AGPL-3.0
component  : programming.ide
summary    : Integrated development environment (IDE) for R
description: |
    RStudio is an integrated development environment (IDE) for the R programming language.
networking : yes
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libR)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(libpq)
    - pkgconfig(sqlite3)
    - pkgconfig(yaml-cpp)
    - apache-ant
    - libboost-devel
    - pandoc
    - shared-mime-info
    - soci-devel
    - xdg-utils
    - yarn
rundeps    :
    - r
setup      : |
    # Defeat build 'checks'
    pushd dependencies/common
    install -d dictionaries libclang/{3.5,builtin-headers} mathjax-27 rmarkdown rsconnect node/10.19.0/bin
    ln -s $workdir/dependencies/common/dictionaries $workdir/dependencies/dictionaries
    ln -s $workdir/dependencies/common/mathjax-27 $workdir/dependencies/mathjax-27
    ln -s $workdir/dependencies/common/pandoc $workdir/dependencies/pandoc

    # Couldn't check PATH obviously.
    ln -s /usr/bin/node $workdir/dependencies/common/node/10.19.0/bin/

    # Need to grep version and symlink from PATH, ugly af.
    _pandocver=$(grep -oP "(?<=PANDOC_VERSION=\").*(?=\"$)" install-pandoc)
    install -d pandoc/${_pandocver}
    ln -sfT /usr/bin/pandoc pandoc/${_pandocver}/pandoc
    ln -sfT /usr/bin/pandoc-citeproc pandoc/${_pandocver}/pandoc-citeproc
    popd

    # Enable panmirror support
    pushd $workdir/src/gwt/panmirror/src/editor
    yarn config set ignore-engines true
    yarn install
    popd

    %cmake_ninja -DRSTUDIO_TARGET=Desktop \
           -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake \
           -DCMAKE_INSTALL_PREFIX=/usr/share/rstudio \
           -DRSTUDIO_USE_SYSTEM_BOOST=ON \
           -DRSTUDIO_USE_SYSTEM_SOCI=ON \
           -DRSTUDIO_USE_SYSTEM_YAML_CPP=ON \
           -DRSTUDIO_BOOST_SIGNALS_VERSION=2
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d -m 00755 $installdir/usr/bin
    ln -s /usr/share/rstudio/bin/rstudio $installdir/usr/bin/rstudio

    #Use system dictionaries
    rm -rf $installdir/usr/share/rstudio/resources/dictionaries
    ln -s /usr/share/hunspell $installdir/usr/share/rstudio/resources/dictionaries
    # Fix mimetype handlers by replacing desktop file
    install -Dm00644 $pkgfiles/rstudio.desktop $installdir/usr/share/applications/rstudio.desktop

